#!/bin/bash

echo "/**"
echo " * This file is automaticly generated by genregs.sh. Please do not edit it."
echo " * Created at `date`"
echo " */"
echo ""

echo "#ifndef __MACH_G9TV_REGISTER_H"
echo "#define __MACH_G9TV_REGISTER_H"
echo ""

gawk -f register.awk			ucode/register.h
gawk -f c_always_on_pointer.awk		ucode/c_always_on_pointer.h
gawk -f dos_register.awk		ucode/dos_register.h
gawk -f ddr3_reg.awk			ucode/ddr3_reg.h
gawk -f dmc_reg.awk			ucode/dmc_reg.h
gawk -f c_stb_define.awk		ucode/c_stb_define.h
gawk -f secure_apb.awk			ucode/secure_apb.h
gawk -f hdmitx.awk			ucode/hdmitx.h

echo ""
echo "#endif"
