obj-$(CONFIG_AM_WIFI_SD_MMC) +=  wifi_dt.o
obj-$(CONFIG_AM_WIFI) += wifi_power.o
obj-$(CONFIG_DHD_USE_STATIC_BUF) += dhd_static_buf.o
obj-$(CONFIG_RTL8188EU_MP) += rtl8xxx_EU_MP/
obj-$(CONFIG_SDIO_DHD_CDC_WIFI_40181_MODULE) += broadcm_40181/
