
# Makefile for osd and tv
obj-$(CONFIG_AM_TV_OUTPUT)	+= vout/
obj-$(CONFIG_AM_TCON_OUTPUT)	+= vout/
obj-$(CONFIG_AM_GE2D)		+= ge2d/
obj-$(CONFIG_FB_AM)		+= osd/
obj-$(CONFIG_AM_FB_EXT)		+= osd_ext/
obj-y						+= lcd/
obj-$(CONFIG_AM_LOGO)		+= aml_logo/

obj-y				+= backlight/

obj-$(CONFIG_AM_TV_OUTPUT2)	+= vout2/
obj-$(CONFIG_AMLOGIC_SYS_LED)	+= sys_led/
