obj-$(CONFIG_AML_HDMI_TX_20)		+= hdmitx2.o

hdmitx2-objs := hdmi_tx_main.o hdmi_tx_cec.o hdmi_cec_key.o hdmi_tx_video.o hdmi_tx_audio.o hdmi_tx_edid.o hdmi_tx_audio.o hdmi_tx_hdcp.o hdmi_tx_scdc.o

#EXTRA_CFLAGS += -O2
